[package]
name = "surf-report-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
argfile = "0.2.0"
clap = { version = "4.5.4", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"